services:
    ger.livetopicupdate.controller:
        class: ger\livetopicupdate\controller\main
        arguments:
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@content.visibility'
            - '@language'

    ger.livetopicupdate.listener:
        class: ger\livetopicupdate\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
